<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Salary Slip</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #2c3e50; }
        .container { width: 100%; padding: 25px; border: 1px solid #dcdcdc; }
        .header { text-align: center; border-bottom: 3px solid #0d6efd; padding-bottom: 12px; margin-bottom: 25px; }
        .company { font-size: 18px; font-weight: bold; }
        .month { font-size: 13px; color: #555; margin-top: 4px; }
        .section-title { font-size: 13px; font-weight: bold; margin: 20px 0 10px; color: #0d6efd; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
        .info-table, .salary { width: 100%; border-collapse: collapse; margin-top: 15px; }
        .info-table td, .salary td, .salary th { padding: 6px 4px; border: 1px solid #ddd; }
        .salary th { background: #0d6efd; color: #fff; font-size: 12px; text-align: left; }
        .salary tr:nth-child(even) { background: #f8f9fa; }
        .total { font-weight: bold; background: #eef3ff; }
        .footer { margin-top: 30px; text-align: center; font-size: 11px; color: #777; }
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <div class="company">Office Management System</div>
        <div class="month">Salary Slip — {{ \Carbon\Carbon::create($salary->year, $salary->month)->format('F Y') }}</div>
    </div>

    <div class="section-title">Employee Information</div>
    <table class="info-table">
        <tr>
            <td><strong>Name</strong></td>
            <td>{{ $salary->employee->first_name }} {{ $salary->employee->last_name }}</td>
            <td><strong>Employee ID</strong></td>
            <td>EMP-{{ str_pad($salary->employee->id,4,'0',STR_PAD_LEFT) }}</td>
        </tr>
        <tr>
            <td><strong>Working Days</strong></td>
            <td>{{ $salary->working_days }}</td>
            <td><strong>Present Days</strong></td>
            <td>{{ $salary->present_days }}</td>
        </tr>
        <tr>
            <td><strong>Paid Leaves</strong></td>
            <td>{{ $salary->leaves }}</td>
            <td><strong>Absent Days</strong></td>
            <td>{{ $salary->absent_days }}</td>
        </tr>
    </table>

    <div class="section-title">Salary Details</div>
    <table class="salary">
        <tr><th>Description</th><th>Amount</th></tr>
        <tr><td>Basic Salary</td><td>{{ number_format($salary->basic_salary,2) }}</td></tr>
        <tr><td>House Allowance</td><td>{{ number_format($salary->house_allowance,2) }}</td></tr>
        <tr><td>Medical Allowance</td><td>{{ number_format($salary->medical_allowance,2) }}</td></tr>
        <tr><td>Transport Allowance</td><td>{{ number_format($salary->transport_allowance,2) }}</td></tr>
        <tr><td>Other Allowance</td><td>{{ number_format($salary->other_allowance,2) }}</td></tr>
        <tr><td>Bonus</td><td>{{ number_format($salary->bonus,2) }}</td></tr>
        <tr class="total"><td>Gross Salary</td><td>{{ number_format($salary->gross_salary,2) }}</td></tr>

        <tr><td>Advance Salary</td><td>{{ number_format($salary->advance_salary,2) }}</td></tr>
        <tr><td>Tax</td><td>{{ number_format($salary->tax,2) }}</td></tr>
        <tr><td>Other Deduction</td><td>{{ number_format($salary->other_deduction,2) }}</td></tr>
        <tr><td>Attendance Deduction</td><td>{{ number_format($salary->deduction,2) }}</td></tr>
        <tr class="total"><td>Total Deductions</td><td>{{ number_format($salary->total_deductions,2) }}</td></tr>

        <tr class="total"><td>Net Salary</td><td>{{ number_format($salary->net_salary,2) }}</td></tr>
    </table>

    <div class="footer">
        Generated by Office Management System
    </div>
</div>
</body>
</html>
